data:
  data_seed: 152
  dataset: dr_fine_tune
  image_folder: dr/sample@1000/
  normalize: true
  num_classes: 2
  root_path: datasets/
  subset_path: dr_subsets/
  unlabeled_frac: 0.90
logging:
  folder: "logs/"
  pretrain_path: paws-latest.pth.tar
  write_tag: paws-latest-SNN
meta:
  copy_data: true
  device: cuda:0
  load_checkpoint: false
  master_port: 4029
  model_name: resnet50
  training: true
  use_fp16: true
optimization:
  epochs: 50
  lr: 0.00001
  use_lars: false
  weight_decay: 0.0
  zero_init: true
