criterion:
  classes_per_batch: 2
  me_max: false
  sharpen: 0.25
  supervised_imgs_per_class: 8
  supervised_views: 1
  temperature: 0.1
  unsupervised_batch_size: 32
data:
  color_jitter_strength: 1.0
  data_seed: null
  dataset: dr
  s_image_folder: dr/sample@2000/
  u_image_folder: dr/train_voets/
  label_smoothing: 0.1
  multicrop: 6
  normalize: true
  root_path: datasets/
  subset_path: dr_subsets
  unique_classes_per_rank: false
  unlabeled_frac: 0.9
logging:
  folder: "logs/"
  write_tag: paws
meta:
  copy_data: true
  device: cuda:0
  load_checkpoint: false
  model_name: resnet50
  output_dim: 2048
  read_checkpoint: null
  use_fp16: true
  use_pred_head: true
optimization:
  epochs: 100
  final_lr: 0.00001
  lr: 0.001
  momentum: 0.9
  nesterov: false
  start_lr: 0.001
  warmup: 10
  weight_decay: 1.0e-06
